### PR TITLE
Issue 6: Adding markdown file support

### PR DESCRIPTION
**Pull request by nguyenhung15913**
- Added a function to read .md file input and convert markdown features inside it into appropriate HTML tags. For now, the tool only converts "#" into "h1".
- E.g: <code># Hello world</code> will be converted into ```<h1>Hello world</h1>```
- README.md has been updated 
- Sample files to test has been added into the project.
- If you have any question, feel free to contact me through hnguyen97@myseneca.ca or reply in this post. Thanks

### CODE REVIEW

**Review by LuigiZaccagnini — CHANGES_REQUESTED** [review]
All code is good! 

Only problem is that your code completely reformats my codes by:

- Removing semicolons
- Changes double quotes to single quotes  

Could you change the style to match mine?

**Comment by nguyenhung15913** [comment]
Sure, I will fix.

**Comment by nguyenhung15913** [comment]
I will send you another pull request after I done fixing.

**Comment by nguyenhung15913** [comment]
I fixed the formatting. Could you please check the request and let me know if there is another issue.

**Review by LuigiZaccagnini — APPROVED** [review]

**Comment by nguyenhung15913** [comment]
Fixes #8

**Comment by LuigiZaccagnini** [comment]
Fixes #7

**Pull request merged**
